# frozen_string_literal: true

# #Kubernetes
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: unversioned
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0-SNAPSHOT
#

$LOAD_PATH.push File.expand_path('lib', __dir__)
require 'zilla/version'

Gem::Specification.new do |s|
  s.name        = 'zilla'
  s.version     = Zilla::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['OpenAPI-Generator']
  s.email       = ['']
  s.homepage    = 'https://openapi-generator.tech'
  s.summary     = 'Kubernetes Ruby Gem'
  s.description = 'No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)'
  s.license     = 'Unlicense'
  s.required_ruby_version = '>= 3.2.0'

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.executables   = []
  s.require_paths = ['lib']
  s.metadata['rubygems_mfa_required'] = 'true'
end
