# frozen_string_literal: true

# #Kubernetes
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: unversioned
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0-SNAPSHOT
#

require 'date'
require 'time'

module Zilla
  # PodStatus represents information about the status of a pod. Status may trail the actual state of a system, especially if the node that hosts the pod cannot contact the control plane.
  class IoK8sApiCoreV1PodStatus
    # Current service state of pod. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
    attr_accessor :conditions

    # The list has one entry per container in the manifest. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-and-container-status
    attr_accessor :container_statuses

    # Status for any ephemeral containers that have run in this pod.
    attr_accessor :ephemeral_container_statuses

    # IP address of the host to which the pod is assigned. Empty if not yet scheduled.
    attr_accessor :host_ip

    # The list has one entry per init container in the manifest. The most recent successful init container will have ready = true, the most recently started container will have startTime set. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-and-container-status
    attr_accessor :init_container_statuses

    # A human readable message indicating details about why the pod is in this condition.
    attr_accessor :message

    # nominatedNodeName is set only when this pod preempts other pods on the node, but it cannot be scheduled right away as preemption victims receive their graceful termination periods. This field does not guarantee that the pod will be scheduled on this node. Scheduler may decide to place the pod elsewhere if other nodes become available sooner. Scheduler may also decide to give the resources on this node to a higher priority pod that is created after preemption. As a result, this field may be different than PodSpec.nodeName when the pod is scheduled.
    attr_accessor :nominated_node_name

    # The phase of a Pod is a simple, high-level summary of where the Pod is in its lifecycle. The conditions array, the reason and message fields, and the individual container status arrays contain more detail about the pod's status. There are five possible phase values:  Pending: The pod has been accepted by the Kubernetes system, but one or more of the container images has not been created. This includes time before being scheduled as well as time spent downloading images over the network, which could take a while. Running: The pod has been bound to a node, and all of the containers have been created. At least one container is still running, or is in the process of starting or restarting. Succeeded: All containers in the pod have terminated in success, and will not be restarted. Failed: All containers in the pod have terminated, and at least one container has terminated in failure. The container either exited with non-zero status or was terminated by the system. Unknown: For some reason the state of the pod could not be obtained, typically due to an error in communicating with the host of the pod.  More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-phase
    attr_accessor :phase

    # IP address allocated to the pod. Routable at least within the cluster. Empty if not yet allocated.
    attr_accessor :pod_ip

    # podIPs holds the IP addresses allocated to the pod. If this field is specified, the 0th entry must match the podIP field. Pods may be allocated at most 1 value for each of IPv4 and IPv6. This list is empty if no IPs have been allocated yet.
    attr_accessor :pod_ips

    # The Quality of Service (QOS) classification assigned to the pod based on resource requirements See PodQOSClass type for available QOS classes More info: https://git.k8s.io/community/contributors/design-proposals/node/resource-qos.md
    attr_accessor :qos_class

    # A brief CamelCase message indicating details about why the pod is in this state. e.g. 'Evicted'
    attr_accessor :reason

    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    attr_accessor :start_time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        conditions: :conditions,
        container_statuses: :containerStatuses,
        ephemeral_container_statuses: :ephemeralContainerStatuses,
        host_ip: :hostIP,
        init_container_statuses: :initContainerStatuses,
        message: :message,
        nominated_node_name: :nominatedNodeName,
        phase: :phase,
        pod_ip: :podIP,
        pod_ips: :podIPs,
        qos_class: :qosClass,
        reason: :reason,
        start_time: :startTime
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        conditions: :'Array<IoK8sApiCoreV1PodCondition>',
        container_statuses: :'Array<IoK8sApiCoreV1ContainerStatus>',
        ephemeral_container_statuses: :'Array<IoK8sApiCoreV1ContainerStatus>',
        host_ip: :String,
        init_container_statuses: :'Array<IoK8sApiCoreV1ContainerStatus>',
        message: :String,
        nominated_node_name: :String,
        phase: :String,
        pod_ip: :String,
        pod_ips: :'Array<IoK8sApiCoreV1PodIP>',
        qos_class: :String,
        reason: :String,
        start_time: :Time
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      unless attributes.is_a?(Hash)
        raise ArgumentError,
              'The input argument (attributes) must be a hash in `Zilla::IoK8sApiCoreV1PodStatus` initialize method'
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        unless self.class.attribute_map.key?(k.to_sym)
          raise ArgumentError,
                "`#{k}` is not a valid attribute in `Zilla::IoK8sApiCoreV1PodStatus`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end

        h[k.to_sym] = v
      end

      if attributes.key?(:conditions) && (value = attributes[:conditions]).is_a?(Array)
        self.conditions = value
      end

      if attributes.key?(:container_statuses) && (value = attributes[:container_statuses]).is_a?(Array)
        self.container_statuses = value
      end

      if attributes.key?(:ephemeral_container_statuses) && (value = attributes[:ephemeral_container_statuses]).is_a?(Array)
        self.ephemeral_container_statuses = value
      end

      self.host_ip = attributes[:host_ip] if attributes.key?(:host_ip)

      if attributes.key?(:init_container_statuses) && (value = attributes[:init_container_statuses]).is_a?(Array)
        self.init_container_statuses = value
      end

      self.message = attributes[:message] if attributes.key?(:message)

      self.nominated_node_name = attributes[:nominated_node_name] if attributes.key?(:nominated_node_name)

      self.phase = attributes[:phase] if attributes.key?(:phase)

      self.pod_ip = attributes[:pod_ip] if attributes.key?(:pod_ip)

      if attributes.key?(:pod_ips) && (value = attributes[:pod_ips]).is_a?(Array)
        self.pod_ips = value
      end

      self.qos_class = attributes[:qos_class] if attributes.key?(:qos_class)

      self.reason = attributes[:reason] if attributes.key?(:reason)

      return unless attributes.key?(:start_time)

      self.start_time = attributes[:start_time]
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      []
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        conditions == other.conditions &&
        container_statuses == other.container_statuses &&
        ephemeral_container_statuses == other.ephemeral_container_statuses &&
        host_ip == other.host_ip &&
        init_container_statuses == other.init_container_statuses &&
        message == other.message &&
        nominated_node_name == other.nominated_node_name &&
        phase == other.phase &&
        pod_ip == other.pod_ip &&
        pod_ips == other.pod_ips &&
        qos_class == other.qos_class &&
        reason == other.reason &&
        start_time == other.start_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [conditions, container_statuses, ephemeral_container_statuses, host_ip, init_container_statuses, message,
       nominated_node_name, phase, pod_ip, pod_ips, qos_class, reason, start_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            send("#{key}=", attributes[self.class.attribute_map[key]].map do |v|
                              _deserialize(::Regexp.last_match(1), v)
                            end)
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Zilla.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
