# frozen_string_literal: true

# #Kubernetes
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: unversioned
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0-SNAPSHOT
#

require 'date'
require 'time'

module Zilla
  # Event is a report of an event somewhere in the cluster. It generally denotes some state change in the system. Events have a limited retention time and triggers and messages may evolve with time.  Event consumers should not rely on the timing of an event with a given Reason reflecting a consistent underlying trigger, or the continued existence of events with that Reason.  Events should be treated as informative, best-effort, supplemental data.
  class IoK8sApiEventsV1Event
    # action is what action was taken/failed regarding to the regarding object. It is machine-readable. This field cannot be empty for new Events and it can have at most 128 characters.
    attr_accessor :action

    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    attr_accessor :api_version

    # deprecatedCount is the deprecated field assuring backward compatibility with core.v1 Event type.
    attr_accessor :deprecated_count

    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    attr_accessor :deprecated_first_timestamp

    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    attr_accessor :deprecated_last_timestamp

    attr_accessor :deprecated_source, :metadata, :regarding, :related, :series

    # MicroTime is version of Time with microsecond level precision.
    attr_accessor :event_time

    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    attr_accessor :kind

    # NOTE: is a human-readable description of the status of this operation. Maximal length of the note is 1kB, but libraries should be prepared to handle values up to 64kB.
    attr_accessor :note

    # reason is why the action was taken. It is human-readable. This field cannot be empty for new Events and it can have at most 128 characters.
    attr_accessor :reason

    # reportingController is the name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`. This field cannot be empty for new Events.
    attr_accessor :reporting_controller

    # reportingInstance is the ID of the controller instance, e.g. `kubelet-xyzf`. This field cannot be empty for new Events and it can have at most 128 characters.
    attr_accessor :reporting_instance

    # type is the type of this event (Normal, Warning), new types could be added in the future. It is machine-readable. This field cannot be empty for new Events.
    attr_accessor :type

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        action: :action,
        api_version: :apiVersion,
        deprecated_count: :deprecatedCount,
        deprecated_first_timestamp: :deprecatedFirstTimestamp,
        deprecated_last_timestamp: :deprecatedLastTimestamp,
        deprecated_source: :deprecatedSource,
        event_time: :eventTime,
        kind: :kind,
        metadata: :metadata,
        note: :note,
        reason: :reason,
        regarding: :regarding,
        related: :related,
        reporting_controller: :reportingController,
        reporting_instance: :reportingInstance,
        series: :series,
        type: :type
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        action: :String,
        api_version: :String,
        deprecated_count: :Integer,
        deprecated_first_timestamp: :Time,
        deprecated_last_timestamp: :Time,
        deprecated_source: :IoK8sApiCoreV1EventSource,
        event_time: :Time,
        kind: :String,
        metadata: :IoK8sApimachineryPkgApisMetaV1ObjectMeta,
        note: :String,
        reason: :String,
        regarding: :IoK8sApiCoreV1ObjectReference,
        related: :IoK8sApiCoreV1ObjectReference,
        reporting_controller: :String,
        reporting_instance: :String,
        series: :IoK8sApiEventsV1EventSeries,
        type: :String
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      unless attributes.is_a?(Hash)
        raise ArgumentError,
              'The input argument (attributes) must be a hash in `Zilla::IoK8sApiEventsV1Event` initialize method'
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        unless self.class.attribute_map.key?(k.to_sym)
          raise ArgumentError,
                "`#{k}` is not a valid attribute in `Zilla::IoK8sApiEventsV1Event`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end

        h[k.to_sym] = v
      end

      self.action = attributes[:action] if attributes.key?(:action)

      self.api_version = attributes[:api_version] if attributes.key?(:api_version)

      self.deprecated_count = attributes[:deprecated_count] if attributes.key?(:deprecated_count)

      if attributes.key?(:deprecated_first_timestamp)
        self.deprecated_first_timestamp = attributes[:deprecated_first_timestamp]
      end

      if attributes.key?(:deprecated_last_timestamp)
        self.deprecated_last_timestamp = attributes[:deprecated_last_timestamp]
      end

      self.deprecated_source = attributes[:deprecated_source] if attributes.key?(:deprecated_source)

      self.event_time = attributes[:event_time] if attributes.key?(:event_time)

      self.kind = attributes[:kind] if attributes.key?(:kind)

      self.metadata = attributes[:metadata] if attributes.key?(:metadata)

      self.note = attributes[:note] if attributes.key?(:note)

      self.reason = attributes[:reason] if attributes.key?(:reason)

      self.regarding = attributes[:regarding] if attributes.key?(:regarding)

      self.related = attributes[:related] if attributes.key?(:related)

      self.reporting_controller = attributes[:reporting_controller] if attributes.key?(:reporting_controller)

      self.reporting_instance = attributes[:reporting_instance] if attributes.key?(:reporting_instance)

      self.series = attributes[:series] if attributes.key?(:series)

      return unless attributes.key?(:type)

      self.type = attributes[:type]
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = []
      invalid_properties.push('invalid value for "event_time", event_time cannot be nil.') if @event_time.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @event_time.nil?

      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        action == other.action &&
        api_version == other.api_version &&
        deprecated_count == other.deprecated_count &&
        deprecated_first_timestamp == other.deprecated_first_timestamp &&
        deprecated_last_timestamp == other.deprecated_last_timestamp &&
        deprecated_source == other.deprecated_source &&
        event_time == other.event_time &&
        kind == other.kind &&
        metadata == other.metadata &&
        note == other.note &&
        reason == other.reason &&
        regarding == other.regarding &&
        related == other.related &&
        reporting_controller == other.reporting_controller &&
        reporting_instance == other.reporting_instance &&
        series == other.series &&
        type == other.type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [action, api_version, deprecated_count, deprecated_first_timestamp, deprecated_last_timestamp, deprecated_source,
       event_time, kind, metadata, note, reason, regarding, related, reporting_controller, reporting_instance, series, type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            send("#{key}=", attributes[self.class.attribute_map[key]].map do |v|
                              _deserialize(::Regexp.last_match(1), v)
                            end)
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Zilla.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
